from __future__ import annotations

import json
from contextlib import contextmanager

import anyio
from pytest import MonkeyPatch

from app.mcp.external import create_deck_builder_mcp_app
from app.mcp.server import DeckBuilderMcpServer
from app.models.deck import DeckResponse, Format
from app.rag.retriever import RetrievedDocument


class FakeRetriever:
    def __init__(self, text_documents: list[RetrievedDocument]) -> None:
        self.text_documents = text_documents
        self.last_query: str | None = None
        self.last_source: str | None = None
        self.last_limit: int | None = None

    def search(self, query: str, limit: int = 5, source: str | None = None) -> list[RetrievedDocument]:
        self.last_query = query
        self.last_source = source
        self.last_limit = limit
        return [document for document in self.text_documents if source is None or document.source == source][
            :limit
        ]

    def search_text(
        self,
        query: str,
        limit: int = 5,
        source: str | None = None,
        metadata_filters: dict[str, list[str]] | None = None,
    ) -> list[RetrievedDocument]:
        self.last_query = query
        self.last_source = source
        self.last_limit = limit
        documents = [document for document in self.text_documents if source is None or document.source == source]
        return documents[:limit]

    def search_by_metadata_prefix(
        self,
        source: str,
        metadata_key: str,
        prefixes: list[str],
        limit: int = 10,
    ) -> list[RetrievedDocument]:
        self.last_source = source
        self.last_limit = limit
        return [
            document
            for document in self.text_documents
            if document.source == source
            and any(str(document.metadata.get(metadata_key) or "").startswith(prefix) for prefix in prefixes)
        ][:limit]


def test_external_mcp_app_lists_the_deck_builder_tool_surface() -> None:
    retriever = FakeRetriever(
        [
            RetrievedDocument(
                title="Comprehensive Rules",
                content="A player draws a card.",
                source="mtg_comprehensive_rules",
                metadata={"section": "120.1"},
            )
        ]
    )

    @contextmanager
    def server_context():
        yield DeckBuilderMcpServer(retriever=retriever)

    mcp = create_deck_builder_mcp_app(server_context_factory=server_context)

    async def list_tools() -> set[str]:
        tools = await mcp.list_tools()
        return {tool.name for tool in tools}

    assert anyio.run(list_tools) == {
        "build_deck",
        "search_rag_text",
        "search_rag_vector",
        "search_rag_metadata_prefixes",
        "search_strategy",
        "search_meta_decks",
        "search_rules",
        "search_card_corpus",
        "search_cards_scryfall",
        "lookup_card",
        "validate_deck_cards",
    }


def test_external_mcp_app_routes_tool_calls_through_the_shared_server() -> None:
    retriever = FakeRetriever(
        [
            RetrievedDocument(
                title="Comprehensive Rules",
                content="A player draws a card.",
                source="mtg_comprehensive_rules",
                metadata={"section": "120.1"},
            )
        ]
    )

    @contextmanager
    def server_context():
        yield DeckBuilderMcpServer(retriever=retriever)

    mcp = create_deck_builder_mcp_app(server_context_factory=server_context)

    async def call_search_rules() -> dict[str, object]:
        result = await mcp.call_tool("search_rules", {"intent": "draw a card", "limit": 1})
        return json.loads(result[0].text)

    payload = anyio.run(call_search_rules)

    assert payload["title"] == "Comprehensive Rules"
    assert retriever.last_query == "draw a card"
    assert retriever.last_source == "mtg_comprehensive_rules"
    assert retriever.last_limit == 1


def test_external_mcp_app_build_deck_routes_through_the_web_app_pipeline(monkeypatch: MonkeyPatch) -> None:
    class FakeSession:
        def __init__(self) -> None:
            self.closed = False

        def close(self) -> None:
            self.closed = True

    fake_session = FakeSession()
    captured: dict[str, object] = {}

    async def fake_generate_deck(request, session):  # type: ignore[no-untyped-def]
        captured["request"] = request.model_dump(mode="json")
        captured["session"] = session
        return DeckResponse(
            title="Modern Tempo",
            format=Format.modern,
            cards=[{"name": "Lightning Bolt", "count": 4, "role": "burn"}],
            sideboard=[],
            explanation="Generated by the web app pipeline.",
            mana_curve=[],
            validation={"is_valid": True, "errors": [], "warnings": []},
            retrieved_context=["Lightning Bolt (scryfall_bulk)"],
            agent_steps=[],
            generation_mode="deterministic",
        )

    @contextmanager
    def server_context():
        yield DeckBuilderMcpServer(retriever=FakeRetriever([]))

    monkeypatch.setattr("app.mcp.external.SessionLocal", lambda: fake_session)
    monkeypatch.setattr("app.mcp.external.generate_deck", fake_generate_deck)

    mcp = create_deck_builder_mcp_app(server_context_factory=server_context)

    async def call_build_deck() -> dict[str, object]:
        result = await mcp.call_tool(
            "build_deck",
            {
                "format": "modern",
                "budget_usd": 150,
                "colors": ["U", "R"],
                "playstyle": "tempo",
                "strategy": "efficient threats and cheap interaction",
                "must_include": ["Lightning Bolt"],
                "avoid": ["Ragavan, Nimble Pilferer"],
            },
        )
        return json.loads(result[0].text)

    payload = anyio.run(call_build_deck)

    assert payload["title"] == "Modern Tempo"
    assert payload["format"] == "modern"
    assert captured["request"] == {
        "format": "modern",
        "budget_usd": 150.0,
        "colors": ["U", "R"],
        "playstyle": "tempo",
        "strategy": "efficient threats and cheap interaction",
        "must_include": ["Lightning Bolt"],
        "avoid": ["Ragavan, Nimble Pilferer"],
    }
    assert captured["session"] is fake_session
    assert fake_session.closed is True
